### PR TITLE
Contact form

### PR DESCRIPTION
**Pull request by ROHAN842**
I have successfully made contact form for the website 

Fixes Issue #70 

https://user-images.githubusercontent.com/61961107/124941771-ae266e80-e028-11eb-9764-913b71fd1699.mp4

### CODE REVIEW

**Comment by ROHAN842** [comment]
Hey @hkaur008 please merge my PR

**Comment by hkaur008** [comment]
Can you remove colorful part?

**Comment by ROHAN842** [comment]
@hkaur008 which colorful part that scrollbar one ?

**Comment by hkaur008** [comment]
> @hkaur008 which colorful part that scrollbar one ?

colorfull scrollbar

**Comment by ROHAN842** [comment]
Hey @hkaur008 kindly close this PR and merge the updated #75 one

**Comment by hkaur008** [comment]
okay

**Pull request closed without merging**
